### ISSUE TITLE
Mac OS X only supports an opengl context up to v4.1

### ISSUE THREAD

**Issue by maikz** [cgcostume/cgexamples#1]

**Comment by scheibel** [comment]
This is by design of OS X. What is your actual issue here?
No support of compute shaders?

**Comment by maikz** [comment]
With context 4.2 no glfw-window is created and the program returns right after

``` c++
GLFWwindow * window = glfwCreateWindow(canvasWidth, canvasHeight, "", nullptr, nullptr);
```

in the main function (glfw error 0x10007).

**Comment by scheibel** [comment]
Which example? sky-triangle? particles? sat?

**Comment by scheibel** [comment]
I think we explicitly query for OpenGL 4.2 to use uniform locations. This is optional and can be changed.
