### ISSUE TITLE
On OS X with a retina display the viewport is much smaller than the window

### ISSUE THREAD

**Issue by maikz** [cgcostume/cgexamples#2]
Screen coordinates and pixels of a retina display do not map 1:1 so that the dimensions of the examples are much smaller than the window they are shown in. Using the dimensions of the standard framebuffer to resize the examples fixes the problem.

**Comment by scheibel** [comment]
This is a known problem with a known solution using GLFW, it seems like our default fix isn't integrated into these programs hosted here.
